apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - default.yaml
  - database.yaml
  - elastic-system.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - longhorn-system.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - vault.yaml
  - velero.yaml
  - nextcloud.yaml
  - kubernetes-dashboard.yaml
  - open-webui.yaml
  - kube-cronjob-system.yaml
