apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-oauth2-proxy-secret
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1m
  data:
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: open-webui
        property: oauth-cookie-secret
    - secretKey: CLIENT_ID
      remoteRef:
        key: open-webui
        property: oauth-client-id
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: open-webui
        property: oauth-client-secret
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-webui-oauth2-proxy
spec:
  interval: 24h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui-oauth2-proxy
spec:
  interval: 10m
  chart:
    spec:
      version: 10.x
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: open-webui-oauth2-proxy
  values:
    envFrom:
      - secretRef:
          name: open-webui-oauth2-proxy-secret
    extraArgs:
      - --http-address=0.0.0.0:4180
      - --provider=github
      - --github-user=piny940
      - --client-id=$(CLIENT_ID)
      - --client-secret=$(CLIENT_SECRET)
      - --cookie-secret=$(COOKIE_SECRET)
      - --redirect-url=https://stg-openai.piny940.com/oauth2/callback
      - --whitelist-domain=*.piny940.com
      - --upstream=http://open-webui.open-webui.svc.cluster.local
      - --skip-auth-route=
      - --cookie-secure=true
    ingress:
      enabled: true
      className: nginx
      path: /
      pathType: Prefix
      hosts:
        - stg-openai.piny940.com
      tls:
        - hosts:
            - stg-openai.piny940.com
          secretName: cluster-tls
