apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
spec:
  numberOfInstances: 1
  databases:
    clubroom_staging: default.clubroom
    kintai_staging: default.kintai
    portfolio_staging: default.portfolio
    song_list_staging: default.song-list
    auth_staging: default.auth
    nextcloud: nextcloud.nextcloud
