apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-oauth2-proxy-conf-1
data:
  authenticated_emails_file: |
    piny940
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-oauth2-proxy-secret
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1m
  data:
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: longhorn
        property: oauth-cookie-secret
    - secretKey: CLIENT_ID
      remoteRef:
        key: longhorn
        property: oauth-client-id
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: longhorn
        property: oauth-client-secret
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-oauth2-proxy
spec:
  interval: 24h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-oauth2-proxy
spec:
  interval: 10m
  chart:
    spec:
      version: 8.x
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: longhorn-oauth2-proxy
  values:
    envFrom:
      - secretRef:
          name: longhorn-oauth2-proxy-secret
    extraArgs:
      - --http-address=0.0.0.0:4180
      - --provider=github
      - --client-id=$(CLIENT_ID)
      - --client-secret=$(CLIENT_SECRET)
      - --cookie-secret=$(COOKIE_SECRET)
      - --upstream=http://longhorn-frontend.longhorn-system.svc.cluster.local:80
      - --skip-auth-route=
      - --cookie-secure=true
      - --authenticated-emails-file=/etc/oauth2-proxy-config/authenticated_emails_file
      - --skip-provider-button
      - --github-user=piny940
    extraVolumes:
      - name: oauth2-proxy
        configMap:
          name: longhorn-oauth2-proxy-conf-1
          items:
            - key: authenticated_emails_file
              path: authenticated_emails_file
    extraVolumeMounts:
      - name: oauth2-proxy
        mountPath: /etc/oauth2-proxy-config
        readOnly: true
    ingress:
      enabled: true
      className: nginx
      path: /
      pathType: Prefix
      hosts:
        - longhorn.piny940.com
      tls:
        - hosts:
            - longhorn.piny940.com
          secretName: cluster-tls
