[project]
name = "ansible-workspace"
version = "0.1.0"
description = "Ansible workspace"
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
  "ansible==12.3.0",
  "ansible-lint==26.2.0",
  "passlib==1.7.4",
  "pyyaml==6.0.3",
]
