apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
resources:
  - ../base
labels:
  - pairs:
      env: production
    includeSelectors: true
configMapGenerator:
  - name: open-webui-conf
    behavior: merge
    literals:
      - GITHUB_CLIENT_ID=Ov23liQnnPEPWDtRyF5J
